### ISSUE TITLE
Step 2: a & b > c

### ISSUE THREAD

**Issue by cfgauss** [everhartlab/IntroR_2019#3]
The question was "Are both a and b greater than c?" where `a == 5`, `b == 1`, and `c == 3`. This is coded as
```
(a > c) & (b > c)
```
Since `>` is higher in precedence than `&`, the parentheses are optional. `5 & 1 > 3` is evaluated as `5 & (1 > 3)` . This is `5 & FALSE`. Since any non-zero double will be coerced to TRUE, this is `TRUE & FALSE` or `FALSE`, an "accidentally-correct" answer. Note that `0 & 1 > -1` returns `FALSE` but `(0 > -1) & (1 > -1)` returns `TRUE`. Similarly "Is either a or b greater than c?" is
```
(a > c) | (b > c)
```

**Comment by nikitagambhir** [comment]
Thanks for letting me know! I did not know about this :) I have updated the code.
